[project]
name = "myfirstproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ncca-ngl>=0.1.6",
    "numpy>=2.3.3",
]
